version: '2'

services:
   core:
     build:
        context: .
     container_name: 'winterbowl'
     ports:
       - "5000:80"
     restart: always
     environment:
       ASPNETCORE_ENVIRONMENT: development
     volumes:
       - .:/dotnetapp
